### ISSUE TITLE
User account and system settings prefill

### ISSUE THREAD

**Issue by leslietech** [PaulLebmann/docker-gibbonedu#3]
Thanks for the work that you have done in this repo. The more that I test it, the more I realize how complex it is (to me, that is)...lol.

Do the changes that you made in 9ce40438b8c88c93ce08308b3f57a44d06888ee2 also mean that we will not be able to preset the values for the installer step #3 "installer/install.php?step=3"? I was wondering if it will still be possible to inject the values for the following fields:
- Title
- Surname
- First Name
- Email
- Receive Support
- Username
- System Name
- Install Type
- Organization Name
- Organization Initials
I never really asked why it was failing to prefill the database field values.

**Comment by PaulLebmann** [comment]
Never mind - I'm just dabbling in this stuff myself.

Yes, you're right. You can not preset any of those values. At least it's my impression.
I just tried copying a working config.php in place it seems that as soon gibbon gets a database (and a connection) it think's it is already installed and throws an error about its missing tables.

Therefore you have to enter all your setup information by hand.
The data from step 3 seems to be written to the database. As long as gibbon itself does not read shell environment variables to prepopulate the fields I don't see a way to do it from outside.

It would be nice to prepopulate some fields since the data is already needed to configure the other containers but this would probably mean to rethink the check if Gibbon is already installed. When the config.php is read and Gibbon would check for it's tables and then decide if it's installed or not would enable the possibility for the fields during installation to be prepopulated by values in config.php. But this would mean an additional database query every time the site is loaded. Just deciding based on the existence of config.php is faster.

I think, since it is only once you have to enter the data, the faster loading times on every site call (think large schools with hundreds of students and lots of parallel queries) are to prefer.

**Comment by leslietech** [comment]
> I think, since it is only once you have to enter the data, the faster loading times on every site call (think large schools with hundreds of students and lots of parallel queries) are to prefer.

Good point. My objective was to speed up the install process if I have to deploy lots of these sites. I am also working on learning to create a template site and then export the db to a new site and then update the values (site name, url...etc). However, I am ok with the way things are. You are the only one that I know that has Dockerized Gibbon. I'm grateful for what you have done. You will not believe how many test sites I have already created with your repo...lol. I just cloned it and then added Traefik labels to it.

**Comment by PaulLebmann** [comment]
To achieve this you could use the database dump of a newly setup gibbon site without user generated data, and add a shell script to:

1. replace the strings in the database dump to the values you want put in in step 3
2. and copy the database dump to ./db/init.db

Since you now have a working database after starting your compose project for the first time, you could also modify php/docker-php-gibbonsetup to generate a config.php or create a config.php with the same shell script and mount it to /var/www/html/config.php in your docker-compose.yml.

You could keep your variables all in your .env file and use them inside your containers and in the shell script to setup the database template.

The downside, of course, would be, that you have to recreate your database - template with every new version of Gibbon. On the other hand, with this setup you can easy spin up another instance under another name with exported data from your production site.

Did you add the traefik labels via docker-compose.override.yml or direct in docker-compose.yml?

I'm glad this repo is useful for you. I also chose this setup for easy testing and resetting if necessary. I'm sad to say, that I was not able to use Gibbon in production at our school.

**Comment by leslietech** [comment]
We can close this issue.
