### ISSUE TITLE
Upgrade to v24.0.00

### ISSUE THREAD

**Issue by leslietech** [PaulLebmann/docker-gibbonedu#4]
Hi Paul. This is not is much an issue because you have not yet updated this repo to v24. I used this experience to learn how you have build this image/repo, and know how to troubleshoot issues. I went ahead of you this time by attempting an upgrade from v23.0.02 to v24.0.00

![image](https://user-images.githubusercontent.com/49253776/175846023-00df5851-8c5e-4509-a3fb-9e3335d76680.png)

![image](https://user-images.githubusercontent.com/49253776/175846108-39d2e648-1763-4036-b53c-b90c250e4983.png)

After updating the version nu8mber in the .env file, I get the following when I log into Gibbon:

![image](https://user-images.githubusercontent.com/49253776/175846464-bcde24fb-1b56-4c9f-b3a3-460f7e4fd5c6.png)

To work around this, I revert to an older version of PHP, that is:
```
# FROM php:8.1-fpm-alpine as minimum
FROM php:7.4.29-fpm-alpine3.16 as minimum
```
I got the PHP version idea from [here](https://www.projeqtor.org/en/forum/5-ask-questions/11385-error-pdo-object-is-uninitialized).

![image](https://user-images.githubusercontent.com/49253776/175846921-2b174700-67d5-40c6-a080-d2219a3eebc9.png)

![image](https://user-images.githubusercontent.com/49253776/175846973-7f36df6f-1cfe-44e2-abf1-a94b7e7e3ec4.png)

After this successfull upgrade, I went an extra step by using the php:8.1-fpm-alpine image and it was successful.

![image](https://user-images.githubusercontent.com/49253776/175847559-be4fbda2-b8c6-4280-bb54-62e6764706c8.png)

Database version:

![image](https://user-images.githubusercontent.com/49253776/175847710-108bccf7-d35f-41c0-8aff-cc74cebc5de2.png)

**Comment by PaulLebmann** [comment]
Interesting.
Since PHP 8.1. is recommended it should work. Maybe the problem is, that I am using MariaDB and not MySQL. Since the Gibbon download site shows the recommended versions which are also the maximum recommended version of the respective software, MariaDB could differ too much from MySQL and cause the problem.
As soon as I find the time I'll try it on my setup and I will try using it with MySQL.

**Comment by PaulLebmann** [comment]
Your solution is working for me too.
Installation under php 8.1 is working fine.
Creating a setup with demo data under 23.0.02 and and manually upgrading to 24.0.00 inside the container is working under php 8.1.7

Upgrading via the entrypoint script gives the error.
A difference is, when updating via script it seems is that you get logged out.

Copy pasting the commands from the script in the running container is working and you don't get logged out.

I'll have to investigate further.
I will try to remove the additional upgrade steps (cleaning vendor dir and reinstalling via composer) as soon as I have the time.

**Comment by leslietech** [comment]
Thanks for checking, Paul. I will wait for your response.

**Comment by PaulLebmann** [comment]
So for now I've tested:

- New install with php 7.4 (7.4.30) and upgrade via environment variable works without issues. The user gets logged out, but there is no error on logging in.
- New install with demo data on php 8.1 (8.1.8) and upgrade via environment variable still gives the error after logging in.
- New install with demo data on php 8.0 (8.0.21) and upgrade via environment variable still gives the error after logging in.
- New install with demo data on php 8.1 (8.1.8), removed reinstalling of used composer modules on entrypoint => gives the PDO error and in addition the error that occurred on the upgrade from gibbon 22 to 23
- New install with demo data on php 8.1 (8.1.8) and running through the upgrade commands inside the container works without issues and without logging the user out.
- New install with demo data on php 8.1 (8.1.8), running through the upgrade commands inside the container, changing the environment variable and running docker-compose up -d => gives the PDO error
- New install with demo data on php 8.1 (8.1.8), running through the upgrade commands inside the container with user not logged in => PDO error
- New install with demo data on php 8.1 (8.1.8), changing $GIBBON_VERSION in the container and running docker-php-gibbonsetup inside the container works without issues and without logging the user out. After changing $GIBBON_VERSION in .env it still is working.

Summary:
For now it seems that you have to be logged in (as described in the [update manual](https://docs.gibbonedu.org/administrators/getting-started/updating-gibbon/)) for the upgrade to run smoothly on php > 7.4.
Since the recreation of the container that happens when you change the GIBBON_VERSION variable you are logged out and are not able to apply the database upgrade.

Possible solutions:

1. For now, until November, it would be possible to downgrade php to 7.4.
2. Introduce a GIBBON_UPDATE_TO variable, add a cron job or a delayed task and rely on the user to simultaneously work on the webinterface and the cli to make sure the upgrade runs on php >= 8
3. Try to keep a session active over recreation of the container.

After trying solution 3 it worked - so I'll:
- create a volume to store session files
- configure php to store session files on the volume
- enjoy sessions over recreation of containers

I'll experiment some more and push it in the following days. Please test it when it is available.

**Comment by leslietech** [comment]
Thanks @PaulLebmann. I see that you have recently added the volume. I'll give this another shot.

**Comment by PaulLebmann** [comment]
For me it still works.
If upgrading from an older version of this repo you have to pull the code, rebuild the containers so that php gets the new settings, and restart the php container at least once before changing the Gibbon Version so that the persistent session is available.
